### ISSUE TITLE
amazing

### ISSUE THREAD

**Issue by ptChan** [stormzhang/test#1]
Haha,Bro Zhang,this repo is tested for the Wechat public count users,but two guys star it,so cute friends.
And I,m ur fans who is in ur AD groups.Today,I see ur artical and I want to use my github and mistake English again really.
Good night,bro Zhang.
Best wishes for u~

**Comment by lolstudio** [comment]
@ptChan u are so cute ,  :+1:

**Comment by stormzhang** [comment]
@ptChan Great Job, Translate for you all!
Bro means Brother,
ur means your,
AD means AndroidDeveloper!

**Comment by ptChan** [comment]
Thanks，today,I read ur third article about github,it has so much good way to use the github and I'll try my best to using github.

**Comment by lolstudio** [comment]
You can see that ,This should be useful to you : https://github.com/tiimgreen/github-cheat-sheet :smile:

**Comment by stormzhang** [comment]
@lolstudio 很棒的资料，不过不适合新手！

**Comment by ptChan** [comment]
@lolstudio 
```
谢谢，看了下，很全面啊，值得花时间学习～
```
